version: "3.9"
services:
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:80
      ASPNETCORE_Kestrel__Certificates__Default__Password: keycloak-dotnet
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/keycloak-dotnet.pfx
    ports:
      - "5000:80"
    depends_on:
      - keycloak
    volumes:
      - ~/.aspnet/https:/https:ro

  frontend:
    build:
      context: ./frontend/keycloak-dotnet-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - type: bind
        source: frontend/keycloak-dotnet-frontend/src/
        target: /app/src

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-database:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: 1234admin
      KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/keycloak.crt.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/keycloak.key.pem
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - keycloak-database
    volumes:
      - ./certs:/etc/x509/https/
    command: 
      - start-dev 
      - --https-port=8443
  
  keycloak-database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: 1234admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  certs: