version: "3.9"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-database:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: 1234admin
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-database
    command: start-dev
  
  keycloak-database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: 1234admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: